USE DB_MARKET_LIST;

/*SELECT DE USUSARIO*/

SELECT * FROM TB_USUARIO;

/*SELECT DO USER POR LOGIN E SENHA*/

SELECT * FROM TB_USUARIO 
WHERE
NM_LOGIN = X AND CD_SENHA = X;

/*SELECIONAR TODAS AS LISTAS*/

SELECT * FROM TB_LISTA;

/*SELECIONAR LISTAS DO USUARIO EM ESPECIFICO*/

SELECT * FROM TB_LISTA
WHERE ID_USUARIO = X;

/*SELECIONAR ITEM*/

SELECT * FROM TB_ITEM;

/*SELECIONAR ITEM DA LISTA */

SELECT * FROM TB_ITEM AS TI 
INNER JOIN
TB_ITEM_LISTA AS TIL ON TI.CD_ITEM = TIL.ID_ITEM 
WHERE TIL.ID_LISTA = X;

